openapi: 3.0.0
info:
  version: 1.0.0
  title: real-time-river-level-korea-api
  description: "실시한 하천 수위 현황 API 명세 문서"
tags:
  - name: auth
    description: API key / API secret 으로 발급된 JWT Bearer 토큰 인증 관련 기능
  - name: riverlevel
    description: 하천수위정보 관련 기능
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas:
    JWT_token:
      type: object
      description: |
        Access JWT Token과 Refresh JWT Token 반환 형식
      required:
        - access_token
        - refresh_token
      properties:
        access_token:
          type: string
          description: |
            API 이용 접근 용 Token  

            발급 후 아래와 같이 HTTP header Authorization 항목에 Bearer token으로 포함하세요.  

            HTTP header : {  
              Authorization: Bearer <access_token>  
            }
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        refresh_token:
          type: string
          description: |
            Access Token 재발급 용 Token
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c

    sido_param:
      type: string
      description: |
        "시도" 파라미터
      enum:
        [
          서울특별시,
          부산광역시,
          대구광역시,
          인천광역시,
          광주광역시,
          대전광역시,
          울산광역시,
          세종특별자치시,
          경기도,
          강원도,
          충청북도,
          충청남도,
          전라북도,
          전라남도,
          경상북도,
          경상남도,
          제주특별자치도,
        ]
      example: 서울특별시

    sigungu_param:
      type: string
      description: |
        "시군구" 파라미터 ("시도" 파라미터에 따라 달라짐.)

    river_level_response:
      type: object
      description: |
        하천수위정보 반환 형식
      properties:
        sido_name:
          type: string
        sigungu_length:
          type: integer
          format: int32
        sigungu:
          type: object
          additionalProperties:
            type: object
            required:
              - sigungu_name
              - average_river_level_ratio
              - rivergauge_length
              - rivergauge
            properties:
              sigungu_name:
                type: string
              average_river_level_ratio:
                type: number
                format: double
              rivergauge_length:
                type: integer
                format: int32
              rivergauge:
                type: object
                additionalProperties:
                  type: array
                  items:
                    type: object
                    required:
                      - timestamp
                      - river_name
                      - rivergauge_name
                      - rivergauge_code
                      - current_level
                      - planflood_level
                      - river_level_ratio
                    properties:
                      timestamp:
                        type: string
                        format: date-time
                      river_name:
                        type: string
                      rivergauge_name:
                        type: string
                      current_level:
                        type: number
                        format: double
                      planflood_level:
                        type: number
                        format: double
                      river_level_ratio:
                        type: number
                        format: double

security:
  - bearerAuth: []
paths:
  /auth/signin:
    post:
      tags:
        - auth
      summary: API key / API secret를 통한 Access Token과 Refresh Token 발급
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                api_key:
                  type: string
                  example: 1EEA6DC-JAM4DP2-PHVYPBN-V0XCJ9X
                api_secret:
                  type: string
                  example: 1EEA6DC-JAM4DP2-PHVYPBN-V0XCJ9X
      responses:
        "200":
          description: 인증 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWT_token"
        "400":
          description: 잘못된 요청
        "5XX":
          description: 내부 오류

  /auth/refresh:
    post:
      tags:
        - auth
      summary: Refresh Token을 통한 Access Token과 Refresh Token 발급
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_tokrn:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
      responses:
        "200":
          description: 인증 성공
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/JWT_token"
        "400":
          description: 잘못된 요청
        "5XX":
          description: 내부 오류

  /riverlevel/{sido}:
    get:
      tags:
        - riverlevel
      summary: 요청한 "시도" 내 모든 "시군구"의 관측계 별 하천수위 정보
      description: |
        파라미터 **"sido"**를 통해 모든 "시군구"의 관측계 별 하천수위 정보를 가져올 "시도"를 지정할 수 있습니다.
      parameters:
        - in: path
          name: sido
          required: true
          schema:
            $ref: "#/components/schemas/sido_param"
          description: |
            요청할 "시도"의 한글표기(접미사 표현까지 기입)  
            ex) 서울특별시, 세종특별자치시, 경상북도, 제주특별자치도
      responses:
        "200":
          description: |
            요청 성공  
            각 "시군구" 안에는 관측소 별 하천수위 정보가 포함됩니다.  
            단, 각 관측소 별로 단 한 개의 하천수위 정보만 포함됩니다.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/river_level_response"
              example:
                sido_name: 서울특별시
                sigungu_length: 2
                sigungu:
                  성동구:
                    sigungu_name: 성동구
                    average_river_level_ratio: 0.38856304
                    riverguage_length: 2
                    riverguage:
                      성동교:
                        - timestamp: "2022-08-17T13:30:15Z"
                          river_name: 중량천
                          rivergauge_name: 성동교
                          current_level: 4.96
                          planflood_level: 17.05
                          river_level_ratio: 0.29032258
                      마장2교:
                        - timestamp: "2022-08-17T13:30:15Z"
                          river_name: 청계천
                          rivergauge_name: 마장2교
                          current_level: 8.3
                          planflood_level: 17.05
                          river_level_ratio: 0.48680351
                  마포구:
                    sigungu_name: 마포구
                    average_river_level_ratio: 0.76339869
                    riverguage_length: 1
                    riverguage:
                      - timestamp: "2022-08-17T13:30:15Z"
                        river_name: 홍제천
                        rivergauge_name: 성산2교
                        current_level: 11.68
                        planflood_level: 15.3
                        river_level_ratio: 0.76339869
        "400":
          description: 잘못된 요청
        "401":
          description: 잘못된 인증 정보
        "5XX":
          description: 내부 오류

  /riverlevel/{sido}/{sigungu}:
    get:
      tags:
        - riverlevel
      summary: 요청한 "시도" 내 특정 "시군구"의 관측계 별 하천수위 정보
      description: |
        파라미터 **"sido"**와 **"sigungu"**를 통해 관측계 별 하천수위 정보를 가져올 "시도"와 "시군구"를 지정할 수 있습니다.
      parameters:
        - in: path
          name: sido
          required: true
          schema:
            $ref: "#/components/schemas/sido_param"
          description: |
            요청할 "시도"의 한글표기(접미사 표현까지 기입)  
            ex) 서울특별시, 세종특별자치시, 경상북도, 제주특별자치도
        - in: path
          name: sigungu
          required: true
          schema:
            $ref: "#/components/schemas/sigungu_param"
          example: "성동구"
          description: |
            요청할 "시도" 하위 특정 "시군구"의 한글표기(접미사 표현까지 기입)
            (**주의**: "시도" 하위에 존재하지 않는 "시군구"를 요청할 경우 400 반환)
      responses:
        "200":
          description: |
            요청 성공  
            요청한 "시도" 하위 특정 "시군구" 하천들의 수위정보만 반환한다.  
            이때 각 하천 별 수위정보들은 시간대 별로 여러개가 반환될 수 있다.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/river_level_response"
              example:
                sido_name: 서울특별시
                average_river_level_ratio: 0.9
                sigungu_length: 1
                sigungu:
                  성동구:
                    sigungu_name: 성동구
                    average_river_level_ratio: 0.38856304
                    rivergauge_length: 2
                    rivergauge:
                      성동교:
                        - timestamp: "2022-08-17T13:10:15Z"
                          river_name: 중량천
                          rivergauge_name: 성동교
                          current_level: 4.96
                          planflood_level: 17.05
                          river_level_ratio: 0.29032258
                        - timestamp: "2022-08-17T13:15:15Z"
                          river_name: 중량천
                          rivergauge_name: 성동교
                          current_level: 4.96
                          planflood_level: 17.05
                          river_level_ratio: 0.29032258
                        - timestamp: "2022-08-17T13:20:15Z"
                          river_name: 중량천
                          rivergauge_name: 성동교
                          current_level: 4.96
                          planflood_level: 17.05
                          river_level_ratio: 0.29032258
                        - timestamp: "2022-08-17T13:25:15Z"
                          river_name: 중량천
                          rivergauge_name: 성동교
                          current_level: 4.96
                          planflood_level: 17.05
                          river_level_ratio: 0.29032258
                        - timestamp: "2022-08-17T13:30:15Z"
                          river_name: 중량천
                          rivergauge_name: 성동교
                          current_level: 4.96
                          planflood_level: 17.05
                          river_level_ratio: 0.29032258
                      마장2교:
                        - timestamp: "2022-08-17T13:10:15Z"
                          river_name: 청계천
                          rivergauge_name: 마장2교
                          current_level: 8.3
                          planflood_level: 17.05
                          river_level_ratio: 0.48680351
                        - timestamp: "2022-08-17T13:15:15Z"
                          river_name: 청계천
                          rivergauge_name: 마장2교
                          current_level: 8.3
                          planflood_level: 17.05
                          river_level_ratio: 0.48680351
                        - timestamp: "2022-08-17T13:20:15Z"
                          river_name: 청계천
                          rivergauge_name: 마장2교
                          current_level: 8.3
                          planflood_level: 17.05
                          river_level_ratio: 0.48680351
                        - timestamp: "2022-08-17T13:25:15Z"
                          river_name: 청계천
                          rivergauge_name: 마장2교
                          current_level: 8.3
                          planflood_level: 17.05
                          river_level_ratio: 0.48680351
                        - timestamp: "2022-08-17T13:30:15Z"
                          river_name: 청계천
                          rivergauge_name: 마장2교
                          current_level: 8.3
                          planflood_level: 17.05
                          river_level_ratio: 0.48680351
        "400":
          description: 잘못된 요청
        "401":
          description: 잘못된 인증 정보
        "5XX":
          description: 내부 오류

servers:
  # Added by API Auto Mocking Plugin
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/SKYMIN0417/real-time-river-level-korea-api/1.0.0
