import { createRef } from "react";

export const seoulRegions: Regions = {
  강동구: {
    guName: "강동구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  송파구: {
    guName: "송파구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  강남구: {
    guName: "강남구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  서초구: {
    guName: "서초구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  관악구: {
    guName: "관악구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  동작구: {
    guName: "동작구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  영등포구: {
    guName: "영등포구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  금천구: {
    guName: "금천구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  구로구: {
    guName: "구로구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  강서구: {
    guName: "강서구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  양천구: {
    guName: "양천구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  마포구: {
    guName: "마포구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  서대문구: {
    guName: "서대문구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  은평구: {
    guName: "은평구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  노원구: {
    guName: "노원구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  도봉구: {
    guName: "도봉구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  강북구: {
    guName: "강북구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  성북구: {
    guName: "성북구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  중량구: {
    guName: "중량구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  동대문구: {
    guName: "동대문구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  광진구: {
    guName: "광진구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  성동구: {
    guName: "성동구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  용산구: {
    guName: "용산구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  중구: {
    guName: "중구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
  종로구: {
    guName: "종로구",
    target: createRef<SVGPathElement>(),
    riverLevel: [],
    averageRiverLevelRatio: null,
  },
};
